# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples

on:
  push:
    paths: 
      - cv.Rmd
      
name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown", "pagedown"))'

      - name: Render CV
        run: Rscript -e 'rmarkdown::render("cv.Rmd")'

      - name: Commit Results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit cv.html -m 'Re-render CV' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
